In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

#### FEATURE ENCODING
##### Converting text data into numeric data to feed into maching learning model.

In [ ]:
bank = pd.read_csv("../../datasets/bank_original_dataset.csv")

bank.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
bank["Job"].value_counts()

Job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [5]:
bank["Education"].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [6]:
## Oridinal column ---> Education ---> OrdinalEncoder
## Label Encoder   ---> TARGET    ---> LableEncoder
## Hominal colun   ---> Married, ....

In [7]:
ordinal_data = bank[['Education']]

target_data = bank[['TARGET']]

In [8]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['unknown', 'primary', 'secondary', 'tertiary']])

ordinal_data = oe.fit_transform(ordinal_data)

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

target_data = le.fit_transform(target_data)

/home/ankur-anand/miniconda3/envs/genai/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [10]:
bank.columns

Index(['Age', 'Job', 'Marital', 'Education', 'Default', 'Balance', 'Housing',
       'Loan', 'contact', 'Day', 'Month', 'Duration', 'Campaign', 'Pdays',
       'Previous', 'poutcome', 'TARGET'],
      dtype='str')

In [13]:
nominal_data = bank[['Job', 'Marital', 'Default', 'Housing',
       'Loan', 'contact', 'Month', 'poutcome']]

nominal_data

                Job   Marital Default Housing Loan    contact Month poutcome
0        management   married      no     yes   no    unknown   may  unknown
1        technician    single      no     yes   no    unknown   may  unknown
2      entrepreneur   married      no     yes  yes    unknown   may  unknown
3       blue-collar   married      no     yes   no    unknown   may  unknown
4           unknown    single      no      no   no    unknown   may  unknown
...             ...       ...     ...     ...  ...        ...   ...      ...
45206    technician   married      no      no   no   cellular   nov  unknown
45207       retired  divorced      no      no   no   cellular   nov  unknown
45208       retired   married      no      no   no   cellular   nov  success
45209   blue-collar   married      no      no   no  telephone   nov  unknown
45210  entrepreneur   married      no      no   no   cellular   nov    other

[45211 rows x 8 columns]

In [12]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

nominal_data = ohe.fit_transform(nominal_data)

nominal_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 361688 stored elements and shape (45211, 40)>