In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
st = pd.read_csv("../datasets/student_dataset.csv")

st.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [3]:
st.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [4]:
### FEATURE SELECTION

st = st[['Gender', 'Age', 'City', 'Profession', 'Academic Pressure', 'CGPA', 'Study Satisfaction',
         'Sleep Duration', 'Dietary Habits', 'Work/Study Hours','Financial Stress', 
         'Family History of Mental Illness', 'Depression']]

In [6]:
### LABEL ENCODING

from sklearn.preprocessing import LabelEncoder

l = LabelEncoder()

st['Gender'] = l.fit_transform(st['Gender'])
st['Age'] = l.fit_transform(st['Age'])
st['City'] = l.fit_transform(st['City'])
st['Profession'] = l.fit_transform(st['Profession'])
st['Academic Pressure'] = l.fit_transform(st['Academic Pressure'])
st['CGPA'] = l.fit_transform(st['CGPA'])
st['Study Satisfaction'] = l.fit_transform(st['Study Satisfaction'])
st['Sleep Duration'] = l.fit_transform(st['Sleep Duration'])
st['Dietary Habits'] = l.fit_transform(st['Dietary Habits'])
st['Work/Study Hours'] = l.fit_transform(st['Work/Study Hours'])
st['Financial Stress'] = l.fit_transform(st['Financial Stress'])
st['Family History of Mental Illness'] = l.fit_transform(st['Family History of Mental Illness'])
st['Depression'] = l.fit_transform(st['Depression'])

st.head()

,Gender,Age,City,Profession,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,15,51,11,5,266,2,0,0,3,0,0,1
1,0,6,3,11,2,62,5,0,1,3,1,1,0
2,1,13,44,11,3,133,5,2,0,9,0,1,0
3,0,10,49,11,3,34,2,1,1,4,4,1,1
4,0,7,16,11,4,207,3,0,1,1,0,0,0

In [9]:
### Seperating input and output data

X = st[['Gender', 'Age', 'City', 'Profession', 'Academic Pressure', 'CGPA',
       'Study Satisfaction', 'Sleep Duration', 'Dietary Habits',
       'Work/Study Hours', 'Financial Stress',
       'Family History of Mental Illness']]
Y = st['Depression']

In [10]:
### FEATURE SCALING
from sklearn.preprocessing import StandardScaler

s = StandardScaler()
X = s.fit_transform(X)

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print(X_train.shape) # 80% of input data
print(X_test.shape)  # 20% of input data
print(Y_train.shape) # 80% of output data
print(Y_test.shape)  # 20% of output data

(22320, 12)
(5581, 12)
(22320,)
(5581,)

#### Classification Algorithms

In [12]:
### LOGISTICS REGRESSION

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, Y_train)

y_predict = lr.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test, y_predict))

0.792331123454578

In [ ]:
### DECISION TREE CLASSIFIER

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth=5)
tree.fit(X_train, Y_train)

y_predict = tree.predict(X_test)
print(accuracy_score(Y_test, y_predict))

0.7729797527324852

In [18]:
### DECISION TREE CLASSIFIER

from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, Y_train)

y_predict = forest.predict(X_test)
print(accuracy_score(Y_test, y_predict))

0.7840888729618348

In [ ]:
'''
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimators=100)

from catboost import CatBoostClassifier
cat =  CatBoostClassifier(n_estimators=100)
'''

In [20]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier(n_estimators=100)
ada.fit(X_train, Y_train)

y_predict = ada.predict(X_test)
print(accuracy_score(Y_test, y_predict))

0.792510302813116

In [21]:
### KNEIGHBORS CLASSIFIERS

from sklearn.neighbors import KNeighborsClassifier

knc = KNeighborsClassifier(n_neighbors=5)
knc.fit(X_train, Y_train)

y_predict = knc.predict(X_test)
print(accuracy_score(Y_test, y_predict))

0.7573911485396883

In [22]:
### SUPPPORT VECTOR CLASSIFIERS

from sklearn.svm import SVC

svc = SVC(kernel='rbf')
svc.fit(X_train, Y_train)

y_predict = svc.predict(X_test)
print(accuracy_score(Y_test, y_predict))

0.7939437376814191

In [23]:
### BERNOULLI NAIVE BAYES

from sklearn.naive_bayes import BernoulliNB

bn = BernoulliNB()
bn.fit(X_train, Y_train)

y_predict = bn.predict(X_test)
print(accuracy_score(Y_test, y_predict))

0.7502239741981723

In [25]:
'''
### BERNOULLI NAIVE BAYES --> Negative values not allowed

from sklearn.naive_bayes import MultinomialNB

mn = MultinomialNB()
mn.fit(X_train, Y_train)

y_predict = mn.predict(X_test)
print(accuracy_score(Y_test, y_predict))
'''

'\n### BERNOULLI NAIVE BAYES --> Negative values not allowed\n\nfrom sklearn.naive_bayes import MultinomialNB\n\nmn = MultinomialNB()\nmn.fit(X_train, Y_train)\n\ny_predict = mn.predict(X_test)\nprint(accuracy_score(Y_test, y_predict))\n'

In [26]:
### BAGGING CLASSIFIER ---> ENSEMBLE LEARNING

from sklearn.ensemble import BaggingClassifier

bag = BaggingClassifier(n_estimators=100)
bag.fit(X_train, Y_train)

y_predict = bag.predict(X_test)
print(accuracy_score(Y_test, y_predict))

0.7719046765812578

In [27]:
### STACKING CLASSIFER --> ENSEMBLE LEARNNG
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier

# Base models
estimators = [
    ('rf', RandomForestClassifier()),
    ('br', BaggingClassifier())
]

# Stacking Regressor
stacking = StackingClassifier(
    estimators=estimators,
    final_estimator=AdaBoostClassifier()
)

# Train the model
stacking.fit(X_train, Y_train)

# Make predictions
y_predict = stacking.predict(X_test)
print(accuracy_score(Y_test, y_predict))

0.7830137968106075

In [32]:
### HYPER PARAMETER TRAINING ---> GRIDSEARCHCV

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {'n_estimators':[100, 200], 'max_depth': [4, 6, 8]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, cv=5)
grid.fit(X_train, Y_train)

print(grid.best_params_)
print(grid.best_score_)

{'max_depth': 8, 'n_estimators': 200}
0.4008182930866976

In [33]:
### HYPER PARAMETER TRAINING ---> RANDOMSEARCHCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {'n_estimators':[100, 200], 'max_depth': [4, 6, 8]}
random = RandomizedSearchCV(RandomForestRegressor(), param_distributions=param_grid, n_iter=10, cv=5)
random.fit(X_train, Y_train)

print(random.best_params_)
print(random.best_score_)

/home/ankur-anand/miniconda3/envs/genai/lib/python3.12/site-packages/sklearn/model_selection/_search.py:326: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

{'n_estimators': 200, 'max_depth': 8}
0.4012890190010173